# works great as of 2/16/2025
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker/jellyfin:/config
      - /data:/data
    ports:
      - 8096:8096
    devices:
     - /dev/dri:/dev/dri # Intel QuickSync
    restart: unless-stopped

  jellyseerr:
      container_name: jellyseerr
      image: fallenbagel/jellyseerr:latest
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Denver
      volumes:
        - /docker/jellyseerr:/app/config
      ports:
        - 5055:5055
      restart: unless-stopped
# Want more!? https://github.com/awesome-jellyfin/awesome-jellyfin
